### ISSUE TITLE
Android Apps support

### ISSUE THREAD

**Issue by seukhyun-han** [wayne-incorporated/wayne-os#57]
Hello!

As a matter of fact FydeOS supports Android Apps. There was a tricky way to run Android Apps on CloudReady too with ARC Welder turning them into Chrome Extensions.

Would be nice to see what it takes to be able to run APKs on ChromiumOS. Maybe we can look at the FydeOS implementation if it's open sourced.

Thank you!

**Comment by evelyn-widyasari-kho** [comment]
Go over legal issue about Android App support in Wayne OS.
