### ISSUE TITLE
PC shut down tab itself when turn on Youtube (happen sometimes when turning on PC for too long but incognito is fine)

### ISSUE THREAD

**Issue by seukhyun-han** [wayne-incorporated/wayne-os#61]

**Comment by evelyn-widyasari-kho** [comment]
After clearing browsing data/cache, Youtube works fine

**Comment by evelyn-widyasari-kho** [comment]
Keep on tracking this kind of bug with Wayne OS 22.06 version.   
And arrange a bug report format with includes OS log/screenshot file for users.
