### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by seukhyun-han** [wayne-incorporated/wayne-os#62]
Reporter: @stepanrumyantsev 
Windows 10 x64 21H2 and Windows 11 x64 21H2.
git version 2.27.0.windows.1
Intel Core i7-7700HQ
16GB RAM

<br>git clone got error.
<br>It happens with Wayne OS repo in Gitlab only. Not other repo in Github.

Receiving objects:  80% (643526/794766), 1.39 GiB | 6.34 MiB/s
<br>Receiving objects:  80% (643526/794766), 1.40 GiB | 5.98 MiB/s
<br>Receiving objects:  80% (643526/794766), 1.40 GiB | 4.04 MiB/s
<br>Receiving objects:  80% (643526/794766), 1.40 GiB | 3.87 MiB/s
<br>Receiving objects:  80% (643526/794766), 1.42 GiB | 5.44 MiB/s
<br>fatal: pack has bad object at offset 1492464431: inflate returned -5

**Comment by bak-seongbin** [comment]
Can't help it.
