### ISSUE TITLE
Which one binary to select.

### ISSUE THREAD

**Issue by qveezzx** [wayne-incorporated/wayne-os#98]
Which binary should i use to download "Wayne OS" as persistent on 64gb usb drive?

**Comment by bak-seongbin** [comment]
The latest 23.11 version support any USB flash drives that has 16GB+ capacity.
To use Google accounts that is registered on Google white list, download "desktop" version.
If not, download kiosk version and customize it.

**Comment by maxed4901** [comment]
Which version of chromeos is used?.
